config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'offers#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :offers, only: [:index, :create, :new, :show, :destroy] do
    resources :bookings, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :image_urls

# validates :title, length: {minimum: 15}
  validates :address, presence: true
  validates :description, length: {minimum: 15}
  validates :instruction, presence: true
  # validates :date, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :offers
  has_many :bookings
  has_many :bookings_as_owner, through: :plants, source: :bookings
  
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :phone_number, presence: true
  # validates :email, format: { with: /\A.*@.*\.com\z/ }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    # before_action :set_booking, only: [ :show ]
    
    def index
        @bookings = Booking.all
    end
    
    def new
        @booking = Booking.new
    end

    def create
        @booking = Booking.new
        # @booking = Booking.find(params[:id])
        @booking.user = current_user
        @offer = Offer.find(params[:offer_id])
        @booking.offer = @offer
        @booking.save
        redirect_to offer_path(@offer)
    end

    def show
      @booking = Booking.find(params[:id])
    end

#     private

#   def booking_params
#     params.require(:booking).permit(:user_id, :offer_id)
#   end

#   def set_booking
#     @booking = Booking.find(params[:id])
#     # authorize @offer
#   end  
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :show, :index]
  before_action :set_offer, only: [ :show, :destroy ]

  def index
      @offers = Offer.all
      @markers = @offers.geocoded.map do |offer|
        {
          lat: offer.latitude,
          lng: offer.longitude
        }
      end
  end

  def new
    @offer = Offer.new
  end

  def show
    @offer = Offer.find(params[:id])
    @booking = Booking.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def destroy
    @offer.destroy
    redirect_to offers_path
  end

  private

  def offer_params
    params.require(:offer).permit(:title, :description, :date, :address, :instruction, :price, image_urls: [])
  end

  def set_offer
    @offer = Offer.find(params[:id])
    # authorize @offer
  end  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:home, :show, :index]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlowerCare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_pack_tag 'application' %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render './shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render './shared/footer' %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/offers/_form.html.erb
<%= form_for(@offer) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :instructions %>
  <%= f.text_field :instruction %>
  <%= f.label :image %>
  <%= f.text_field :image_url %>
  <%= f.label :date %>
  <%= f.date_select :date %>
  <%= f.submit %>
<% end %>

app/views/offers/index.html.erb
<div class="hero-image">
  <div class="hero-text">
   <h1>Flowers deserve love too.</h1>
   <p class="p-3">We let you earn money by taking care of other people's plants while they
   are away. We also make sure your plant babies are taken care off while you are away from your home.'</p>
  </div>
</div>

<%# Search form from Jonathan %>

<div class="col-sm-12 col-lg-6 center_div ">
<%= form_tag offers_path, method: :get, class: "searchform" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control searchinput",
    placeholder: "Find available offers"
  %>
  <%= submit_tag "Search", class: "btn btn-dark width-button" %>
<% end %>
</div>

<%# WIP-cards from Lena %>
<h2 class="section-heading">Explore all flower caring job offers</h2>
<div class="wrapper">
  <div class="cards">
      <% @offers.each do |offer| %>

        <div class="card-trip">
          <% if offer.image_urls.attached? %>
              <%= cl_image_tag offer.image_urls.first.key, crop: :fill %>
          <% end %>
          <div class="card-trip-infos">
            <div>
              <h4><%= link_to offer.address, offer_path(offer) %></h4>
            </div>
            <h4 class="card-trip-pricing">€<%= offer.price %></h4>
          </div>
        </div>
      <% end %>
  </div>

  <div id="map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/offers/new.html.erb
<!-- <h1>What are the specs of your new offer?</h1>
<%= render "form", offer: @offer %>
 -->

<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="bg-white rounded p-3 shadow">
        <h3>New offer</h3>
        <%= simple_form_for @offer do |f| %>
          <%= f.input :title, :label => 'Title:', :required => true %>
          <%= f.input :address, :label => 'Address:' %>
          <%= f.input :description, :label => 'Describe your place:', :required => true %>
          <%= f.input :instruction, :label => 'Instructions for caring for the plants:' %>
          <%= f.input :date, :label => 'Beginning of your vacation:', :required => true %>
          <%= f.input :price, input_html: { min: '0' }, :label => 'Price you want to pay:', :hint => "prices are in €", :required => true %>
          <%= f.input :image_urls, as: :file, input_html: { multiple: true }, :label => 'Please upload images of your plants (max. 5):'  %>
          <%= f.submit class: 'btn btn-flat' %>
        <% end %>
      </div>
    </div>
  </div>
  <%= link_to 'Back', offers_path, class: 'btn btn-flat' %>
</div>

app/views/offers/show.html.erb
<div class="container">
  <h2 class="mt-4"><%= @offer.address %></h2>

<!-- image grid hero -->

<div class="image-grid mt-3">
  <% @offer.image_urls.each_with_index do |image_url, index| %>
    <% if index == 0 %>
      <div class="large-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(image_url.key) %>')">
      </div>
     <% end %>
  <% end %>
  <div class="small-images">
    <% @offer.image_urls.each_with_index do |image_url, index| %>
      <% if index != 0 %>
        <div class="small-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path(image_url.key) %>')">
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<!-- middle section -->

<div class="row mb-5 middle-section">
  <div class="col-6">
    <div class="offer-information">
      <div class="offer-details mt-5 pb-3">
        <h4><%= @offer.user.name %> has 15 plants</h4>
        <p class="mt-3"><%= @offer.description %></p>
      </div>
      <div class="offer-instruction mt-3">
        <h4 class="mt-3">Instructions</h4>
        <p class="mt-3"><%= @offer.instruction %></p>
      </div>
    </div>
  </div>

  <!-- booking card -->

  <div class="col-4 booking-card">
      <%#= simple_form_for [ @offer, @booking ] do |f| %>
          <%#= f.submit "Create booking", class: "btn btn-primary" %>
      <%# end %>
      <h4 class="text-center"><%= @offer.date %></h4>
      <div class="row price-info">
        <div class="price-description col-7">
          <p>If plants are still alive you will be rewarded with:</p>
        </div>
        <div class="price col-3">
          <h2> <%= @offer.price %>€</h2>
        </div>
        <div class="create-booking col-12">
          <%= simple_form_for [ @offer, @booking ] do |f| %>
              <%= f.submit "Book this job", class: "btn btn-block booking-button" %>
          <% end %>
        </div>
      </div>
  </div>
</div>

</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_url('banner.jpeg') %>);">
  <div class="container">
    <h1 class="text-center">FLOWER CARE</h1>
    <p class="text-center">Plants in good hands</p>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    We <i class="fas fa-heart"></i> taking care of plants!
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "flower_care_logo_white.svg" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%#= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Create Offer", new_offer_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar_01", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%#= link_to "Action", "#", class: "dropdown-item" %>
            <%#= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>